---
- name: remove previos certs
  ansible.builtin.file:
    path: "{{ cert_path }}"
    state: absent

- name: debug
  debug:
    msg: "{{ subject_alt_name }}"

- name: set CN_FULL fact
  set_fact: 
   CN_FULL: "{{ ('*.' ~ CN) if is_wildcard else CN }}"

- name: "Create dir {{ cert_path }}"
  file:
    path: "{{ cert_path }}"
    state: directory
    mode: 0775

- name: generate private key for letsencrypt account "{{ le_key_path }}/{{ le_key_filename }}"
  community.crypto.openssl_privatekey:
    path: "{{ le_key_path }}/{{ le_key_filename }}"
    force: yes
    size: 4096

- name: "generate private key for {{ CN }} in {{ cert_path }}"
  community.crypto.openssl_privatekey:
    path: "{{ cert_path }}/{{ priv_key }}"
    force: yes
    size: 4096

- name: "create request {{ cert_path }}/{{ csr_file  }}  {{ CN_FULL}}"
  community.crypto.openssl_csr:
    path: "{{ cert_path }}/{{ csr_file  }}"
    privatekey_path: "{{ cert_path }}/{{ priv_key }}"
    email_address: "{{ email_address }}"
    common_name: "{{ CN_FULL }}"
  when: subject_alt_name is not defined

- name: "create request {{ cert_path }}/{{ csr_file  }}"
  community.crypto.openssl_csr:
    path: "{{ cert_path }}/{{ csr_file  }}"
    privatekey_path: "{{ cert_path }}/{{ priv_key }}"
    email_address: "{{ email_address }}"
    common_name: "{{ CN_FULL }}"
    subject_alt_name: "{{ subject_alt_name }}"
  when: subject_alt_name is defined

- name: "Create a challenge for {{ CN_FULL }} using a account key from a variable."
  acme_certificate:
    account_email: "{{ email_address }}"
    account_key_src: "{{ le_key_path }}/{{ le_key_filename }}"
    src: "{{ cert_path }}/{{ csr_file }}"
    dest: "{{ cert_path }}/{{ cert_name }}"
    acme_directory: "{{ acme_directory }}"
    terms_agreed: 1
    acme_version: 2
    challenge: dns-01
    force: yes
  register: challenge

- name: debug
  debug:
    msg: "{{ challenge }}"

- name: "Create TXT record {{ CN }}"
  community.general.cloudflare_dns:
    domain: "{{ CN }}"
    record: "{{ challenge.challenge_data[CN_FULL]['dns-01'].record }}"
    type: TXT
    ttl: 60
    value: "{{ challenge.challenge_data[CN_FULL]['dns-01'].resource_value }}"
    solo: true
    account_email: "{{ cloudflare_email_address }}"
    account_api_key: "{{ cloudflare_account_api_key }}"
    state: present
  when: subject_alt_name is not defined

- name: "Create TXT records {{ item }}"
  community.general.cloudflare_dns:
    domain: "{{ CN }}"
    record: "{{ challenge.challenge_data[item | regex_replace('^DNS:(.*)$', '\\1') ]['dns-01'].record }}"
    type: TXT
    ttl: 60
    value: "{{ challenge.challenge_data[item | regex_replace('^DNS:(.*)$', '\\1') ]['dns-01'].resource_value }}"
    account_email: "{{ cloudflare_email_address }}"
    account_api_key: "{{ cloudflare_account_api_key }}"
    state: present
  with_items: "{{ subject_alt_name }}"
  when: subject_alt_name is defined

- name: Wait 30 seconds
  ansible.builtin.pause:
    seconds: 30

- name: Let the challenge be validated and retrieve the cert and intermediate certificate
  community.crypto.acme_certificate:
    account_key_src: "{{ le_key_path }}/{{ le_key_filename }}"
    account_email: "{{ email_address }}"
    csr: "{{ cert_path }}/{{ csr_file  }}"
    cert: "{{ cert_path }}/{{ cert_name }}"
    fullchain: "{{ cert_path }}/{{ cert_fullchain }}"
    chain: "{{ cert_path }}/{{ cert_chain }}"
    challenge: dns-01
    terms_agreed: 1
    acme_version: 2
    acme_directory: "{{ acme_directory }}"
    remaining_days: 60
    data: "{{ challenge }}"
  when: challenge is changed

- name: Remove temp files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ le_key_path }}/{{ le_key_filename }}"
    - "{{ cert_path }}/{{ csr_file  }}"

- name: set permissions
  ansible.builtin.file:
    path: '{{ cert_path }}'
    owner: root
    group: jenkins
    mode: u=rwX,g=rX,o=rX 
    recurse: yes
